vich_uploader:
    db_driver: orm

    mappings:
       avatar:
            uri_prefix: /images/avatar
            upload_destination: '%kernel.project_dir%/public/images/avatar'
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
